services:
  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:8081"
    environment:
      - DB_URL=${DB_URL_AUTH}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_URL=http://user-service:8080
      - SHOW_SQL=${SHOW_SQL}
    depends_on:
      - auth-db
      - user-service
    networks:
      - innowise-network
    restart: unless-stopped

  # User Service
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=${DB_URL_USER}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - user-db
      - redis
    networks:
      - innowise-network
    restart: unless-stopped

  # Databases
  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    networks:
      - innowise-network
    restart: unless-stopped

  user-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${USER_DB_PORT}:5432"
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    networks:
      - innowise-network
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - innowise-network
    restart: unless-stopped

volumes:
  auth-postgres-data:
  user-postgres-data:
  order-postgres-data:
  redis-data:

networks:
  innowise-network:
    driver: bridge