spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL:false}

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${DB_SCHEMA:public}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_service}
    driver-class-name: org.postgresql.Driver

  redis:
    cache:
      type: redis
      redis:
        time-to-live: 300000
        cache-null-values: false
  data:
    redis:
      port: 6379
      timeout: 2000ms
      host: localhost